name: Trigger an Azure Machine Learning job on main pushes

on:
  workflow_dispatch:
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Submit job
      run: az ml job create -f src/job.yml --resource-group rg-redi-dev --workspace-name amlws-redi-dev


