name: Trigger an Azure Machine Learning job PRs to main

on:
  workflow_dispatch:
    pull_request:
      branches:
        - main
jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Placeholder
      run: |
        echo "Will add code checks here in next challenge"