name: Shift traffic on push to main

on:
  push:
    branches:
      - main

jobs:
  shift-traffic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Set default workspace and resource group
        run: az configure --defaults group=rg-redi-dev workspace=amlws-redi-dev
      - name: Move traffic to new deployment
        run: az ml online-deployment update  -f ./src/deployment.yml --all-traffic
