name: Trigger training jobs on PRs to main

on:
  workflow_dispatch:

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Set default workspace and resource group
        run: az configure --defaults group=rg-redi-dev workspace=amlws-redi-dev
      - name: Submit job
        run: az ml job create -f src/job.yml --stream
  production:
    runs-on: ubuntu-latest
    needs: experiment
    steps:
      - name: Check out repo
        uses: actions/checkout@main
      - name: Install az ml extension
        run: az extension add -n ml -y
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Set default workspace and resource group
        run: az configure --defaults group=rg-redi-dev workspace=amlws-redi-dev
      - name: Substitute prod values
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.inputs.training_data.path = "../production/data" | .experiment_name = "mslearn-mlops-tutorial-experiment-prod"' ./src/job.yml
      - name: Submit job
        run: az ml job create -f src/job-prod.yml
